plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.admaker.ai'
    compileSdk 35

    defaultConfig {
        applicationId 'com.admaker.ai'
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }
}

flutter {
    source '../..'
}
